### ISSUE TITLE
master节点operator-agent无法获取ip

### ISSUE THREAD

**Issue by Xu-Wentao** [kasynap/kasynap#1]
**k8s环境**
```bash
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

查看pod日志

[agent.log](https://github.com/kasynap/kasynap/files/8121651/agent.log)

**Comment by SimpCosm** [comment]
> **k8s环境**
> 
> ```shell
> Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> 查看pod日志
> 
> [agent.log](https://github.com/kasynap/kasynap/files/8121651/agent.log)

可否输出下以下命令的结果 @Xu-Wentao 

```
$ kubectl get enis -oyaml
$ kubectl get sn -oyaml
```

**Comment by Xu-Wentao** [comment]
> > **k8s环境**
> > ```shell
> > Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
> > Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 查看pod日志
> > [agent.log](https://github.com/kasynap/kasynap/files/8121651/agent.log)
> 
> 可否输出下以下命令的结果 @Xu-Wentao
> 
> ```
> $ kubectl get enis -oyaml
> $ kubectl get sn -oyaml
> ```

`kubectl get snis -oyaml`
输出内容
<img width="513" alt="截屏2022-02-23 上午11 30 57" src="https://user-images.githubusercontent.com/9206873/155257607-9ba86a71-a228-4f7f-98f7-f4e7fa5be1dc.png">
`kubectl get sn -oyaml`
输出内容
```bash
[root@bj5-testing-k8s-master01 ~]# kubectl get sn -oyaml
apiVersion: v1
items:
- apiVersion: synap.io/v1alpha1
  kind: SynapNode
  metadata:
    creationTimestamp: "2022-02-22T13:00:21Z"
    generation: 1
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: bj5-testing-k8s-master01.tccn.idc.xiaomi.com
      kubernetes.io/os: linux
      node-role.kubernetes.io/control-plane: ""
      node-role.kubernetes.io/master: ""
      node.kubernetes.io/exclude-from-external-load-balancers: ""
    name: bj5-testing-k8s-master01.tccn.idc.xiaomi.com
    ownerReferences:
    - apiVersion: v1
      kind: Node
      name: bj5-testing-k8s-master01.tccn.idc.xiaomi.com
      uid: 2de9459b-7de6-4c54-ae6f-2aa88526a9f5
    resourceVersion: "3550"
    uid: a04be35f-05e4-4984-a192-85ca65f5c5f8
  spec:
    addresses:
    - ip: 10.95.0.7
      type: InternalIP
    instanceID: ins-og3e4jj7
    instanceType: S5.LARGE16
    ipam:
      shareENI:
        max-above-watermark: 4
        min-allocate: 8
        pre-allocate: 8
    placement:
      zone: ap-beijing-5
    provider: TencentCloud
    subnetID: subnet-oytyhswh
    vpcID: vpc-cdmpo5za
  status:
    ipam:
      shareENI: {}
- apiVersion: synap.io/v1alpha1
  kind: SynapNode
  metadata:
    creationTimestamp: "2022-02-22T13:03:58Z"
    generation: 1
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: bj5-testing-k8s-slave01.tccn.idc.xiaomi.com
      kubernetes.io/os: linux
    name: bj5-testing-k8s-slave01.tccn.idc.xiaomi.com
    ownerReferences:
    - apiVersion: v1
      kind: Node
      name: bj5-testing-k8s-slave01.tccn.idc.xiaomi.com
      uid: 4cfd55af-641a-41be-a90f-290ae99234d6
    resourceVersion: "3880"
    uid: d1cdd66c-b4f7-416c-b7f9-f3a9acacbe57
  spec:
    addresses:
    - ip: 10.95.0.13
      type: InternalIP
    instanceID: ins-lf1v5oa7
    instanceType: S5.LARGE16
    ipam:
      shareENI:
        max-above-watermark: 4
        min-allocate: 8
        pre-allocate: 8
    placement:
      zone: ap-beijing-5
    provider: TencentCloud
    subnetID: subnet-oytyhswh
    vpcID: vpc-cdmpo5za
  status:
    ipam:
      shareENI: {}
- apiVersion: synap.io/v1alpha1
  kind: SynapNode
  metadata:
    creationTimestamp: "2022-02-22T13:04:11Z"
    generation: 1
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: bj5-testing-k8s-slave02.tccn.idc.xiaomi.com
      kubernetes.io/os: linux
    name: bj5-testing-k8s-slave02.tccn.idc.xiaomi.com
    ownerReferences:
    - apiVersion: v1
      kind: Node
      name: bj5-testing-k8s-slave02.tccn.idc.xiaomi.com
      uid: 85ee51be-e926-444d-9b6d-48fcc034a8ce
    resourceVersion: "3914"
    uid: c7dd46d9-1127-4710-8a49-fcd95482abab
  spec:
    addresses:
    - ip: 10.95.0.16
      type: InternalIP
    instanceID: ins-osdwy2h5
    instanceType: S5.LARGE16
    ipam:
      shareENI:
        max-above-watermark: 4
        min-allocate: 8
        pre-allocate: 8
    placement:
      zone: ap-beijing-5
    provider: TencentCloud
    subnetID: subnet-oytyhswh
    vpcID: vpc-cdmpo5za
  status:
    ipam:
      shareENI: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by SimpCosm** [comment]
> 

没有分配 ENI ，可否发下 operator 的日志 @Xu-Wentao

**Comment by Xu-Wentao** [comment]
> > 
> 
> 没有分配 ENI ，可否发下 operator 的日志 @Xu-Wentao
看起来像是operator请求的时候认证有问题
[operator.log](https://github.com/kasynap/kasynap/files/8121769/operator.log)

**Comment by SimpCosm** [comment]
> > > 
> > 
> 没有分配 ENI ，可否发下 operator 的日志 @Xu-Wentao
> > 看起来像是operator请求的时候认证有问题
> > [operator.log](https://github.com/kasynap/kasynap/files/8121769/operator.log)

是的，请检查 secret 配置是否正确，注意这里 ConfigMap 里面应该是经过 base64 编码过的

![image](https://user-images.githubusercontent.com/16812977/155258518-d2a7f2c0-55fc-4e52-a3b5-6dd141725bef.png)

**Comment by Xu-Wentao** [comment]
> > > >
> > 
> > 
> > 没有分配 ENI ，可否发下 operator 的日志 @Xu-Wentao
> > > 看起来像是operator请求的时候认证有问题
> > > [operator.log](https://github.com/kasynap/kasynap/files/8121769/operator.log)
> 
> 是的，请检查 secret 配置是否正确，注意这里 ConfigMap 里面应该是经过 base64 编码过的
> 
> ![image](https://user-images.githubusercontent.com/16812977/155258518-d2a7f2c0-55fc-4e52-a3b5-6dd141725bef.png)

确认已经base64编码过了，一开始的时候忘记编码提示环境变量有问题。
![image](https://user-images.githubusercontent.com/9206873/155259190-9930224e-f66d-4c8c-b001-c0b0580b3a46.png)
